version: "3.8"

services:
  web:
    build: .
    container_name: saw-api-web
    ports:
      - "7080:80"
    volumes:
      - ./:/var/www/html/
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-root}
      DB_PASS: ${DB_PASS:-root}
      DB_NAME: ${DB_NAME:-saw15}
    networks:
      - atende
    restart: unless-stopped

networks:
  atende:
    external: true
